<?php if (!defined('ABSPATH')) { exit; } ?><!doctype html>
<html <?php language_attributes(); ?>><head><meta charset="<?php bloginfo('charset'); ?>"><meta name="viewport" content="width=device-width,initial-scale=1"><?php wp_head(); ?></head>
<body <?php body_class(); ?>><?php wp_body_open(); ?>
<header class="qd-nav"><div class="qd-shell qd-navin"><a class="qd-brand" href="<?php echo esc_url(home_url('/')); ?>"><span class="qd-orb"></span><span>QuantDeus</span></a><nav class="qd-links"><a href="#holding">Холдинг</a><a href="#services">Услуги</a><a href="#ksenia">Ксения</a><a href="#community">Сообщество</a></nav></div></header>
<main>
<section class="qd-hero" id="holding"><div class="qd-shell"><div class="qd-kicker">QuantDeus Holding · WordPress Core</div><h1>Неоновый горизонт</h1><p>Исследования, автоматизация, продукты, медиа и сообщество в едином WordPress-контуре с человеческим контролем и проверяемыми результатами.</p><div class="qd-actions"><a class="qd-btn" href="#services">Оставить заявку</a><a class="qd-btn alt" href="#community">Сообщество</a></div></div></section>
<section class="qd-section"><div class="qd-shell"><h2>Направления</h2><div class="qd-grid"><article class="qd-card"><span class="qd-tag">AI</span><h3>Автоматизация</h3><p>Интеграции, AI-агенты, бизнес-процессы и прикладные цифровые системы.</p></article><article class="qd-card"><span class="qd-tag">R&D</span><h3>Исследования</h3><p>Научные гипотезы, evidence gates, космос, энергия и технологии будущего.</p></article><article class="qd-card"><span class="qd-tag">Media</span><h3>Культура</h3><p>Креативные проекты, выступления, медиа и эстетика Cosmic Frutiger Aero.</p></article></div></div></section>
<section class="qd-section" id="services"><div class="qd-shell"><h2>Услуги</h2><div class="qd-grid"><?php
$services=get_posts(['post_type'=>'qd_service','post_status'=>'publish','numberposts'=>20]);
foreach($services as $s): $sid=get_post_meta($s->ID,'qd_service_id',true) ?: $s->post_name; ?>
<article class="qd-card"><span class="qd-tag">По запросу</span><h3><?php echo esc_html(get_the_title($s)); ?></h3><p><?php echo esc_html(wp_strip_all_tags($s->post_content)); ?></p><button class="qd-btn" data-service="<?php echo esc_attr($sid); ?>">Оставить заявку</button></article>
<?php endforeach; ?></div><div class="qd-card" id="inquiryBox" hidden style="margin-top:18px"><h3>Заявка без регистрации</h3><form class="qd-form" id="qdInquiry"><input type="hidden" name="service_id"><textarea name="note" minlength="10" maxlength="1600" required placeholder="Опиши задачу или мероприятие"></textarea><input name="contact" maxlength="320" required placeholder="@telegram, телефон или email"><input name="website" tabindex="-1" autocomplete="off" style="position:absolute;left:-9999px"><button class="qd-btn" type="submit">Отправить</button><div class="qd-notice" id="qdInquiryStatus">Заявка сохраняется напрямую в WordPress.</div></form></div></div></section>
<section class="qd-section" id="ksenia"><div class="qd-shell"><h2>Ксения Чередникова</h2><div class="qd-card"><span class="qd-tag">Artist / Booking</span><h3>Концерты и медиа</h3><p>Официальный раздел артиста управляется из WordPress: фото, биография, медиа, ссылки и заявки на выступления.</p><button class="qd-btn" data-service="ksenia-cherednikova-concert">Запросить выступление</button></div></div></section>
<section class="qd-section" id="community"><div class="qd-shell"><h2>Сообщество</h2><div class="qd-card"><p>Форум QuantDeus работает на WordPress posts/comments и REST API. Публикация требует авторизации; чтение открыто.</p><a class="qd-btn alt" href="<?php echo esc_url(home_url('/forum/')); ?>">Открыть форум</a></div></div></section>
</main><footer><div class="qd-shell">QuantDeus · WordPress canonical runtime · no Make dependency</div></footer>
<script>
(()=>{const box=document.getElementById('inquiryBox'),form=document.getElementById('qdInquiry'),status=document.getElementById('qdInquiryStatus');document.querySelectorAll('[data-service]').forEach(b=>b.addEventListener('click',()=>{box.hidden=false;form.service_id.value=b.dataset.service;box.scrollIntoView({behavior:'smooth'})}));form?.addEventListener('submit',async e=>{e.preventDefault();status.textContent='Отправляю…';const fd=new FormData(form),body=Object.fromEntries(fd.entries());try{const r=await fetch('<?php echo esc_js(rest_url('quantdeus/v1/inquiries')); ?>',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)}),d=await r.json();if(!r.ok)throw new Error(d.message||'HTTP '+r.status);status.textContent='Заявка принята WordPress · #'+d.id;form.reset()}catch(err){status.textContent='Ошибка: '+err.message}})})();
</script><?php wp_footer(); ?></body></html>