'use strict';
const fs=require('fs');
const crypto=require('crypto');
const {execFileSync}=require('child_process');
const {reasonRole,renderRole}=require('./openclaw-role-dialogue');
const {isEmhComment,skipDialogue}=require('./dialogue-state');
const repo=process.env.GITHUB_REPOSITORY, token=process.env.GITHUB_TOKEN;
const hubIssue=Number(process.env.QUANTDEUS_COORDINATION_HUB_ISSUE||9);
if(!repo||!token) process.exit(1);
const env={...process.env,GH_TOKEN:token};
const gh=a=>execFileSync('gh',a,{encoding:'utf8',env,stdio:['ignore','pipe','pipe']}).trim();
const j=a=>{const s=gh(a);return s?JSON.parse(s):null};
const labels=i=>(i.labels||[]).map(x=>typeof x==='string'?x:x.name);
const age=(v,now)=>{const t=Date.parse(v||'');return Number.isFinite(t)?Math.max(0,(now-t)/36e5):0};
const normalize=s=>String(s||'').replace(/<!--\s*qd-[^>]+-->/gi,'').replace(/https:\/\/github\.com\/[^\s)]+/gi,'<github-url>').replace(/\s+/g,' ').trim().toLowerCase();

(async()=>{
 const now=Date.now();
 const issues=j(['issue','list','--state','open','--limit','200','--json','number,title,labels,updatedAt'])||[];
 const prs=j(['pr','list','--state','open','--limit','100','--json','number,title,isDraft,reviewDecision,updatedAt'])||[];
 const hub=j(['issue','view',String(hubIssue),'--json','comments'])||{comments:[]};
 const comments=hub.comments||[];
 const externalComments=comments.filter(c=>!isEmhComment(c));
 const blocked=issues.filter(i=>labels(i).includes('coord:blocked'));
 const staleBlocked=blocked.filter(i=>age(i.updatedAt,now)>=24);
 const active=issues.filter(i=>labels(i).includes('coord:active')||labels(i).includes('coord:ready'));
 const staleActive=active.filter(i=>age(i.updatedAt,now)>=48);
 const changesRequested=prs.filter(p=>!p.isDraft&&p.reviewDecision==='CHANGES_REQUESTED');
 const recent6h=externalComments.filter(c=>age(c.createdAt,now)<=6), recent24h=externalComments.filter(c=>age(c.createdAt,now)<=24);
 const degraded=/TRANSIENT_OPENCLAW|LIVE_RESEARCH_UNAVAILABLE|LLM[- ]канал|fatal failure|timed?\s*out|degraded|provider failure/i;
 const degradedSignals=recent24h.filter(c=>degraded.test(String(c.body||''))).length;
 const groups=new Map();
 for(const c of recent24h){const n=normalize(c.body);if(n.length<80||n.includes('emh —'))continue;const d=crypto.createHash('sha256').update(n).digest('hex').slice(0,16);groups.set(d,(groups.get(d)||0)+1);}
 const duplicateOutputs=[...groups.values()].filter(n=>n>=3).reduce((s,n)=>s+n-1,0);
 let heat=0; heat+=Math.min(20,changesRequested.length*5)+Math.min(20,staleBlocked.length*6)+Math.min(15,staleActive.length*3)+Math.min(15,duplicateOutputs*5)+Math.min(15,degradedSignals*4)+(recent6h.length>=20?10:0)+(recent6h.length>=40?5:0); heat=Math.min(100,heat);
 const telemetry={open_issues:issues.length,active_or_ready:active.length,blocked:blocked.length,stale_blocked_24h:staleBlocked.length,stale_active_48h:staleActive.length,changes_requested:changesRequested.length,hub_comments_6h:recent6h.length,degraded_signals_24h:degradedSignals,duplicate_outputs_24h:duplicateOutputs,synaptic_heat:heat};
 const digest=crypto.createHash('sha256').update(JSON.stringify(telemetry)).digest('hex').slice(0,12);
 const marker='<!-- qd-emh-digest:'+digest+' -->';
 if(skipDialogue(comments,marker)) return;
 const result=await reasonRole({profile:'emh',role:'EMH — Swarm Cognitive Hygiene & Mediation Officer',context:{telemetry,recent_open_work:active.slice(0,30).map(i=>({number:i.number,title:i.title,labels:labels(i),updatedAt:i.updatedAt})),changes_requested:changesRequested.slice(0,20)},repository:repo,protocol:'Treat metrics as software-system telemetry, never as human diagnosis. Diagnose retry loops, duplicate work, stale handoffs and runtime degradation. Recommend the smallest reversible intervention; do not use fixed status prose.'});
 const report={timestamp:new Date(now).toISOString(),scope:'software-agent telemetry',telemetry,result};
 fs.writeFileSync('/tmp/quantdeus-emh-cognitive-health.json',JSON.stringify(report,null,2));
 const metrics=['Telemetry: heat **'+heat+'/100** · blocked **'+blocked.length+'** · stale active **'+staleActive.length+'** · duplicate pressure **'+duplicateOutputs+'** · degraded signals **'+degradedSignals+'**'];
 if (result.status !== 'DEGRADED' || !skipDialogue(comments,marker,'issue_comment')) gh(['issue','comment',String(hubIssue),'--body',renderRole({heading:'🩺 **EMH — OpenClaw Swarm Health Officer**',result,marker,metrics})]);
})().catch(e=>{console.error(e);process.exitCode=1});
