const { loadState, saveState, gh, ghJson, editIssueLabels, commentIssue } = require('./lib');
function main() {
  const state = loadState();
  const branch = state.execution.branch;
  const existing = ghJson(['pr','list','--head',branch,'--state','all','--json','number,url,state,title']);
  let pr = existing && existing[0];
  if (!pr) {
    const body = `Closes #${state.issue.number}\n\n## Squad B execution\n\n${state.plan.summary}\n\n### Files\n${state.execution.changed_files.map(x=>`- \`${x}\``).join('\n')}\n\nGuardian: **${state.guardian.verdict}**\nRisk: **${state.analysis.risk}**\n\nGenerated by QuantDeus Octet Squad B. No automatic merge.`;
    const url = gh(['pr','create','--head',branch,'--base','main','--title',`[Squad B] ${state.issue.title}`,'--body',body]);
    pr = ghJson(['pr','view',url,'--json','number,url,state,title']);
  }
  editIssueLabels(state.issue.number, ['squad-b:review'], ['squad-b:active','squad-b:blocked']);
  commentIssue(state.issue.number, `📣 **Octet Squad B completed execution.**\n\nPR: ${pr.url}\nBranch: \`${branch}\`\nGuardian: ${state.guardian.verdict}\n\nHuman review/merge is required.`);
  saveState({ pr, stage:'review' });
  console.log(`Herald opened PR ${pr.url}`);
}
main();
