const { loadState, saveState, gh, ghJson, editIssueLabels, commentIssue } = require('./lib');

function main() {
  const state = loadState();
  const branch = state.execution.branch;
  const existing = ghJson(['pr','list','--head',branch,'--state','all','--json','number,url,state,title']);
  let pr = existing && existing[0];

  if (!pr) {
    const body = `Closes #${state.issue.number}\n\n## Squad B execution\n\n${state.plan.summary}\n\n### Files\n${state.execution.changed_files.map(x=>`- \`${x}\``).join('\n')}\n\nGuardian: **${state.guardian.verdict}**\nRisk: **${state.analysis.risk}**\n\nGenerated by QuantDeus Octet Squad B. No automatic merge.`;

    try {
      const url = gh(['pr','create','--head',branch,'--base','main','--title',`[Squad B] ${state.issue.title}`,'--body',body]);
      pr = ghJson(['pr','view',url,'--json','number,url,state,title']);
    } catch (e) {
      const detail = String(e.stderr?.toString() || e.message || e);
      if (!/not permitted to create or approve pull requests|createPullRequest/i.test(detail)) throw e;

      const repo = process.env.GITHUB_REPOSITORY;
      const handoffUrl = `https://github.com/${repo}/compare/main...${branch}?expand=1`;
      editIssueLabels(state.issue.number, ['squad-b:review'], ['squad-b:active','squad-b:blocked']);
      commentIssue(
        state.issue.number,
        `📣 **PR Herald: execution complete; PR handoff required.**\n\nBranch: \`${branch}\`\nOpen PR: ${handoffUrl}\n\nGitHub Actions policy currently prevents GITHUB_TOKEN from creating pull requests. The branch and execution archive are ready for Control Tower / GitHub connector.`
      );
      saveState({ pr:null, handoff:{ url:handoffUrl, reason:'github-actions-pr-policy' }, stage:'review-handoff' });
      console.log(`Herald handed off PR creation: ${handoffUrl}`);
      return;
    }
  }

  editIssueLabels(state.issue.number, ['squad-b:review'], ['squad-b:active','squad-b:blocked']);
  commentIssue(state.issue.number, `📣 **Octet Squad B completed execution.**\n\nPR: ${pr.url}\nBranch: \`${branch}\`\nGuardian: ${state.guardian.verdict}\n\nHuman review/merge is required.`);
  saveState({ pr, stage:'review' });
  console.log(`Herald opened PR ${pr.url}`);
}

main();
